# Generated by Django 2.2.3 on 2019-07-08 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('total_time', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('time_spent_hour', models.IntegerField(blank=True)),
                ('time_spent_minute', models.IntegerField(blank=True)),
                ('time_scheduled_hour', models.IntegerField(blank=True)),
                ('time_scheduled_minute', models.IntegerField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('time_trigger', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(blank=True, related_name='actions', to='tasks.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
