# Generated by Django 2.2.3 on 2019-07-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.Category'),
        ),
    ]
