# Generated by Django 2.2.3 on 2019-08-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190723_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time_scheduled_hour',
            new_name='scheduled_hours',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_scheduled_minute',
            new_name='scheduled_minutes',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_spent_hour',
            new_name='spent_hours',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_spent_minute',
            new_name='spent_minutes',
        ),
    ]
