# Generated by Django 2.2.3 on 2019-08-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190808_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scheduled_hours',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_minutes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='spent_hours',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='spent_minutes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
