# Generated by Django 2.2.3 on 2019-08-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190808_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scheduled_hours',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_minutes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='spent_hours',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='spent_minutes',
            field=models.IntegerField(blank=True),
        ),
    ]
